{
    'name': 'Certification',
    'version': '2.0',
    'category': 'Services',
    'sequence':4,
    'summary': 'Manage machine inspections, checklists, and certificates',
    'depends': ['base', 'web', 'contacts','website'],
    'data': [
        "views/res_partner_views.xml",
        "views/inspection_portal_templates.xml",
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'reports/report_certificate_template.xml',
        'reports/inspection_report.xml',
        'views/inspection_category_views.xml',
        'views/inspection_machine_views.xml',
        'views/inspection_inspection_views.xml',
    ],
    'application': True,
    'installable': True,
}
